# Use a imagem base do Supabase Postgres
FROM supabase/postgres:15.1.0.148

# Instalar dependências necessárias para Node.js
RUN apt-get update && apt-get install -y curl gnupg

# Copie o script de inicialização customizado para o container
COPY init-script.sh /docker-entrypoint-initdb.d/

# Torna o script executável
RUN chmod +x /docker-entrypoint-initdb.d/init-script.sh

# Copie seus scripts de inicialização do banco de dados para o diretório de entrada
#COPY ./dev/postgres/00-setup.sql /docker-entrypoint-initdb.d/

# Copie o projeto Elixir para o container (a pasta raiz do projeto)
COPY . /supavisor

# Expõe a porta 5432 (porta padrão do PostgreSQL)
EXPOSE 5432
